# Generated by Django 2.1.2 on 2018-11-21 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learningresource', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learningresource',
            old_name='department_id',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='learningresource',
            old_name='media_type_id',
            new_name='media_type',
        ),
    ]
