# Generated by Django 2.1.2 on 2018-12-03 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningresource', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningresource',
            name='has_been_upvoted',
        ),
        migrations.AddField(
            model_name='profilelearningresource',
            name='has_been_upvoted',
            field=models.BooleanField(default=False),
        ),
    ]
