# Generated by Django 2.1.2 on 2018-11-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('learningresource', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningresource',
            name='department',
        ),
        migrations.AddField(
            model_name='learningresource',
            name='department',
            field=models.ManyToManyField(to='accounts.Department'),
        ),
    ]
