# Generated by Django 2.1.2 on 2018-11-21 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learningresource', '0002_auto_20181121_1017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learningresourcetag',
            old_name='learningresource_id',
            new_name='learningresource',
        ),
        migrations.RenameField(
            model_name='learningresourcetag',
            old_name='tag_id',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='userlearningresource',
            old_name='learningresource_id',
            new_name='learningresource',
        ),
        migrations.RenameField(
            model_name='userlearningresource',
            old_name='user_id',
            new_name='user',
        ),
    ]
