# Generated by Django 2.1.2 on 2018-11-21 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learningresource', '0003_auto_20181121_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningResourceModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learningresource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learningresource.LearningResource')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(db_index=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='learningresourcemodule',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learningresource.Module'),
        ),
    ]
