# Generated by Django 2.1.2 on 2018-11-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningresource', '0004_auto_20181121_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningresource',
            name='tag',
            field=models.CharField(default='other', max_length=600),
        ),
    ]
