# Generated by Django 2.1.2 on 2018-11-23 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningresource', '0005_auto_20181123_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningresource',
            name='last_edit_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='learningresource',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='learningresource',
            name='url',
            field=models.CharField(max_length=600),
        ),
    ]
