# Generated by Django 2.1.2 on 2018-11-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningresource', '0006_auto_20181123_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningresource',
            name='tag',
            field=models.CharField(default='other', max_length=255),
        ),
    ]
