# Generated by Django 2.1.2 on 2018-12-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_voted',
            field=models.BooleanField(default=False),
        ),
    ]
