# Generated by Django 2.1.2 on 2018-12-03 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181203_2253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiledepartment',
            old_name='current_profile',
            new_name='profile',
        ),
    ]
