# Generated by Django 2.1.2 on 2018-11-27 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181127_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='institution',
            field=models.CharField(choices=[('CODE', 'Code University'), ('CD', 'Code+Design Camps'), ('OTHER', 'other')], default='CODE', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('CD', 'Code+Design Camper'), ('AC_STAFF', 'Academic Staff'), ('ADMIN_STAFF', 'Administrative Staff'), ('ALUMNI', 'Alumni'), ('EXTERNAL', 'External')], max_length=16, null=True),
        ),
        migrations.DeleteModel(
            name='UserType',
        ),
    ]
