# Generated by Django 2.1.2 on 2018-12-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20181203_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiledepartment',
            name='departments',
        ),
        migrations.AddField(
            model_name='profiledepartment',
            name='departments',
            field=models.ManyToManyField(to='accounts.Department'),
        ),
    ]
