# Generated by Django 2.1.2 on 2018-11-30 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20181127_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='institution',
            field=models.CharField(blank=True, choices=[('CODE', 'Code University'), ('CD', 'Code+Design Camps'), ('OTHER', 'other')], default='CODE', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('STUDENT', 'Student'), ('CD', 'Code+Design Camper'), ('AC_STAFF', 'Academic Staff'), ('ADMIN_STAFF', 'Administrative Staff'), ('ALUMNI', 'Alumni'), ('EXTERNAL', 'External')], default='STUDENT', max_length=16, null=True),
        ),
    ]
