# Generated by Django 2.1.2 on 2018-11-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_department_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='department_id',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='department_id',
            field=models.ManyToManyField(to='accounts.Department'),
        ),
    ]
