# Generated by Django 2.1.2 on 2018-11-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20181121_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='department_id',
            field=models.ManyToManyField(blank=True, to='accounts.Department'),
        ),
    ]
